name: CI Pipeline

on:
  pull_request:
    branches:
      - main # Trigger workflow on PRs to the main branch

jobs:
  test:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11" # Ensure compatibility with your FastAPI dependencies

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --no-cache-dir -r requirements.txt

      - name: Run tests with pytest
        run: |
          source venv/bin/activate
          pytest
